namespace TDesign;
/// <summary>
/// 图标名称。
/// </summary>
public enum IconName
{
    [CssClass("add-circle")] AddCircle,
    [CssClass("add-rectangle")] AddRectangle,
    [CssClass("add")] Add,
    [CssClass("app")] App,
    [CssClass("arrow-down-rectangle")] ArrowDownRectangle,
    [CssClass("arrow-down")] ArrowDown,
    [CssClass("arrow-left")] ArrowLeft,
    [CssClass("arrow-right")] ArrowRight,
    [CssClass("arrow-up")] ArrowUp,
    [CssClass("attach")] Attach,
    [CssClass("backtop-rectangle")] BacktopRectangle,
    Backtop,
    Backward,
    Barcode,
    Books,
    [CssClass("browse-off")] BrowseOff,
    Browse,
    BulletPoint,
    Calendar,
    Call,
    [CssClass("caret-down-small")] CaretDownSmall,
    [CssClass("caret-down")] CaretDown,
    [CssClass("caret-left-small")] CaretLeftSmall,
    [CssClass("caret-left")] CaretLeft,
    [CssClass("caret-right-small")] CaretRightSmall,
    [CssClass("caret-right")] CaretRight,
    [CssClass("caret-up-small")] CaretUpSmall,
    [CssClass("caret-up")] CaretUp,
    [CssClass("cart")] Cart,
    [CssClass("chart-bar")] ChartBar,
    [CssClass("chart-bubble")] ChartBubble,
    [CssClass("chart-pie")] ChartPie,
    Chart,
    Chat,
    [CssClass("check-circle-filled")] CheckCircleFilled,
    [CssClass("check-circle")] CheckCircle,
    [CssClass("check-rectangle-filled")] CheckRectangleFilled,
    [CssClass("check-rectangle")] CheckRectangle,
    Check,
    [CssClass("chevron-down-circle")] ChevronDownCircle,
    [CssClass("chevron-down-rectangle")] ChevronDownRectangle,
    [CssClass("chevron-down")] ChevronDown,
    [CssClass("chevron-left-circle")] ChevronLeftCircle,
    [CssClass("chevron-left-rectangle")] ChevronLeftRectangle,
    [CssClass("chevron-left-double")] ChevronLeftDouble,
    [CssClass("chevron-left")] ChevronLeft,
    [CssClass("chevron-right-circle")] ChevronRightCircle,
    [CssClass("chevron-right-rectangle")] ChevronRightRectangle,
    [CssClass("chevron-right-double")] ChevronRightDouble,
    [CssClass("chevron-right")] ChevronRight,
    [CssClass("chevron-up-circle")] ChevronUpCircle,
    [CssClass("chevron-up-rectangle")] ChevronUpRectangle,
    [CssClass("chevron-up")] ChevronUp,
    Circle,
    Clear,
    [CssClass("close-circle-filled")] CloseCircleFilled,
    [CssClass("close-circle")] CloseCircle,
    [CssClass("close-rectangle")] CloseRectangle,
    Close,
    [CssClass("cloud-download")] CloudDownload,
    [CssClass("cloud-upload")] CloudUpload,
    Cloud,
    Code,
    [CssClass("control-platform")] ControlPlatform,
    CreditCard,
    Dashboard,
    Delete,
    Desktop,
    [CssClass("discount-filled")] DiscountFilled,
    Discount,
    Download,
    [CssClass("edit-1")] Edit1,
    Edit,
    Ellipsis,
    Enter,
    [CssClass("error-circle-filled")] ErrorCircleFilled,
    [CssClass("error-circle")] ErrorCircle,
    Error,
    [CssClass("file-add")] FileAdd,
    [CssClass("file-copy")] FileCopy,
    [CssClass("file-excel")] FileExcel,
    [CssClass("file-icon")] FileTIcon,
    [CssClass("file-image")] FileImage,
    [CssClass("file-paste")] FilePaste,
    [CssClass("file-pdf")] FilePdf,
    [CssClass("file-powerpoint")] FilePowerPoint,
    [CssClass("file-unknown")] FileUnknow,
    [CssClass("file-word")] FileWord,
    File,
    [CssClass("filter-clear")] FilterClear,
    Filter,
    Flag,
    [CssClass("folder-add")] FolderAdd,
    [CssClass("folder-open")] FolderOpen,
    Folder,
    Fork,
    [CssClass("format-horizontal-align-bottom")] FormatHorizontalAlignBottom,
    [CssClass("format-horizontal-align-center")] FormatHorizontalAlignCenter,
    [CssClass("format-horizontal-align-top")] FormatHorizontalAlignTop,
    [CssClass("format-vertical-align-left")] FormatVerticalAlignLeft,
    [CssClass("format-vertical-align-right")] FormatVerticalAlignRight,
    [CssClass("format-vertical-align-center")] FormatVerticalAlignCenter,
    Forward,
    [CssClass("fullscreen-exit")] FullScreenExit,
    FullScreen,
    [CssClass("gender-female")] GenderFemale,
    [CssClass("gender-male")] GenderMale,
    Gift,
    [CssClass("heart-filled")] HeartFilled,
    Heart,
    [CssClass("help-circle-filled")] HelpCircleFilled,
    [CssClass("help-circle")] HelpCircle,
    Help,
    History,
    Home,
    Hourglass,
    [CssClass("image-error")] ImageError,
    Image,
    [CssClass("info-circle-filled")] InfoCircleFilled,
    [CssClass("info-circle")] InfoCircle,
    Internet,
    Jump,
    Laptop,
    Layers,
    [CssClass("link-unlink")] LinkUnlink,
    Link,
    Loading,
    Location,
    [CssClass("lock-off")] LockOff,
    [CssClass("lock-on")] LockOn,
    Login,
    [CssClass("logo-android")] LogoAndroid,
    [CssClass("logo-apple-filled")] LogoAppleFilled,
    [CssClass("logo-apple")] LogoApple,
    [CssClass("logo-chrome-filled")] LogoChromeFilled,
    [CssClass("logo-chrome")] LogoChrome,
    [CssClass("logo-codeopen-filled")] LogoCodeOpenFilled,
    [CssClass("logo-codeopen")] LogoCodeOpen,
    [CssClass("logo-github-filled")] LogoGithubFilled,
    [CssClass("logo-github")] LogoGithub,
    [CssClass("logo-ie-filled")] LogoIeFilled,
    [CssClass("logo-ie")] LogoIe,
    [CssClass("logo-qq")] LogoQQ,
    [CssClass("logo-wechat")] LogoWechat,
    [CssClass("logo-wecom")] LogoWecom,
    [CssClass("logo-windows-filled")] LogoWindowsFilled,
    [CssClass("logo-windows")] LogoWindows,
    Logout,
    Mail,
    [CssClass("menu-fold")] MenuFold,
    [CssClass("menu-unfold")] MenuUnfold,
    [CssClass("minus-circle-filled")] MinusCircleFilled,
    [CssClass("minus-circle")] MinusCircle,
    [CssClass("minus-rectangle")] MinusRectangle,
    Mirror,
    [CssClass("mobile-vibrate")] MobileVibrate,
    Mobile,
    [CssClass("money-circle")] MoneyCircle,
    More,
    Move,
    Next,
    [CssClass("notification-filled")] NotificationFilled,
    Notification,
    [CssClass("order-adjustment-column")] OrderAdjustmentColumn,
    [CssClass("order-ascending")] OrderAscending,
    [CssClass("order-descending")] OrderDescending,
    [CssClass("page-first")] PageFirst,
    [CssClass("page-last")] PageLast,
    [CssClass("pause-circle-filled")] PauseCircleFilled,
    Photo,
    [CssClass("pin-filled")] PinFilled,
    Pin,
    [CssClass("play-circle-filled")] PlayCircleFilled,
    [CssClass("play-circle-stroke")] PlayCircleStroke,
    [CssClass("play-circle")] PlayCircle,
    Play,
    PowerOff,
    [CssClass("precise-monitor")] PreciseMonitor,
    Previous,
    Print,
    QrCode,
    Queue,
    Rectangle,
    Refresh,
    Relativity,
    Remove,
    Rollback,
    Rollfront,
    [CssClass("root-list")] RootList,
    Rotation,
    Round,
    Save,
    Scan,
    Search,
    Secured,
    Server,
    Service,
    Setting,
    Share,
    Shop,
    Slash,
    Sound,
    [CssClass("star-filled")] StarFilled,
    Star,
    [CssClass("stop-circle-1")] StopCircle1,
    [CssClass("stop-circle-filled")] StopCircleFilled,
    Stop,
    [CssClass("swag-left")] SwagLeft,
    [CssClass("swag-right")] SwagRight,
    Swag,
    [CssClass("thumb-down")] ThumbDown,
    [CssClass("thumb-up")] ThumbUp,
    [CssClass("time-filled")] TimeFilled,
    Time,
    Tips,
    Tools,
    [CssClass("unfold-less")] UnfoldLess,
    [CssClass("unfold-more")] UnfoldMore,
    Upload,
    USB,
    [CssClass("user-add")] UserAdd,
    [CssClass("user-avatar")] UserAvatar,
    [CssClass("user-circle")] UserCircle,
    [CssClass("user-clear")] UserClear,
    [CssClass("user-talk")] UserTalk,
    User,
    [CssClass("usergroup-add")] UserGroupAdd,
    [CssClass("usergroup-clear")] UserGroupClear,
    UserGroup,
    Video,
    [CssClass("view-column")] ViewColumn,
    [CssClass("view-list")] ViewList,
    [CssClass("view-module")] ViewModule,
    Wallet,
    Wifi,
    [CssClass("zoom-in")] ZoomIn,
    [CssClass("zoom-out")] ZoomOut,
}
